# Generated by Django 5.1.4 on 2025-01-11 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="person_name",
            new_name="name",
        ),
    ]
