# Generated by Django 5.1.4 on 2025-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="reservation_day",
            field=models.CharField(default='Monday', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="seats",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
