# Generated by Django 5.1.4 on 2025-01-11 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drinks",
            old_name="drink_name",
            new_name="drink",
        ),
    ]
